const API_CONFIG = {
  BASE_URL: process.env.REACT_APP_API_BASE_URL,
  POST_SERVICE: process.env.REACT_APP_POST_SERVICE,
  INTERACTION_SERVICE: process.env.REACT_APP_INTERACTION_SERVICE,
  CHAT_SERVICE: process.env.REACT_APP_CHAT_SERVICE,
};

export default API_CONFIG;
