export const FETCH_CONNECTIONS_REQUEST = "FETCH_CONNECTIONS_REQUEST";
export const FETCH_CONNECTIONS_SUCCESS = "FETCH_CONNECTIONS_SUCCESS";
export const FETCH_CONNECTIONS_FAIL = "FETCH_CONNECTIONS_FAIL";

export const SEARCH_USERNAMES_REQUEST = "SEARCH_USERNAMES_REQUEST";
export const SEARCH_USERNAMES_SUCCESS = "SEARCH_USERNAMES_SUCCESS";
export const SEARCH_USERNAMES_FAIL = "SEARCH_USERNAMES_FAIL";
