export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const POST_CONNECT = "POST_CONNECT";
export const POST_REJECT = "POST_REJECT";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";
export const RESET_POST_SUCCESS_NAVIGATE = "RESET_POST_SUCCESS_NAVIGATE";
