export const CONNECT_USER_REQUEST = "CONNECT_USER_REQUEST";
export const CONNECT_USER_SUCCESS = "CONNECT_USER_SUCCESS";
export const CONNECT_USER_FAIL = "CONNECT_USER_FAIL";

export const AVOID_USER_REQUEST = "AVOID_USER_REQUEST";
export const AVOID_USER_SUCCESS = "AVOID_USER_SUCCESS";
export const AVOID_USER_FAIL = "AVOID_USER_FAIL";
